- hosts: cluster
  become: true
  tasks:
  - name: Update apt packages
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Upgrade apt packages
    apt: upgrade=safe force_apt_get=yes
